apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-sensor
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: argo-event-coe
      eventSourceName: webhook
      eventName: custom
  triggers:
    - template:
        name: execute-all
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: basic-flow-event-
              spec:
                entrypoint: basic-flow-event
                templates:
                  - name: basic-flow-event
                    steps:
                      - - name: basic-flow-event
                          templateRef:
                            name: hello-world-custom
                            template: execute-all
