apiVersion: v1
kind: Service
metadata:
  labels:
    webhook: "coe-demo"
  name: webhook-eventsource-coe-svc
  namespace: argo
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    webhook: "coe-demo"
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: argo
  annotations:
    kubernetes.io/ingress.class: nginx
  generation: 1
  labels:
    webhook: "coe-demo"
  name: webhook-eventsource-coe
spec:
  rules:
    - host: argo.testing.coe.com
      http:
        paths:
          - backend:
              serviceName: webhook-eventsource-coe-svc
              servicePort: 8080
            pathType: ImplementationSpecific
            path: /coe-demo
