apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: basic-flow
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: basic-flow
  templates:
    - name: basic-flow
      steps:
        - - name: basic-flow
            templateRef:
              name: hello-world-custom
              template: execute-all
