apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: e2e-hardway-job
  labels:
    workflows.argoproj.io/archive-strategy: "always"
spec:
  entrypoint: execute-e2e
  templates:
    - name: execute-e2e
      steps:
        - - name: set-up-execute-environment
            template: set-up-execute-environment
        - - name: set-up-selenium-packages
            arguments:
              parameters:
                - name: ip
                  value: "{{steps.set-up-execute-environment.ip}}"
            template: set-up-e2e-tests-packages
        - - name: execute-e2e-test
            arguments:
              parameters:
                - name: ip
                  value: "{{steps.set-up-execute-environment.ip}}"
            template: execute-test
    - name: execute-command
      inputs:
        parameters:
          - name: cmd
          - name: ip
      container:
        name: execute-command
        image: ictu/sshpass
        command: ["/bin/sh", "-c"]
        args:
          [
            "sshpass -p root ssh -o StrictHostKeyChecking=no root@{{inputs.parameters.ip}} '{{inputs.parameters.cmd}}'",
          ]
    - name: set-up-e2e-tests-packages
      inputs:
        parameters:
          - name: ip
      steps:
        - - name: upgrade-pip-python-package
            arguments:
              {
                parameters:
                  [
                    { name: cmd, value: "pip install --upgrade pip" },
                    { name: ip, value: "{{inputs.parameters.ip}}" },
                  ],
              }
            template: execute-command
        - - name: install-pip-selenium-packages
            arguments:
              {
                parameters:
                  [
                    {
                      name: cmd,
                      value: "pip install selenium pyvirtualdisplay",
                    },
                    { name: ip, value: "{{inputs.parameters.ip}}" },
                  ],
              }
            template: execute-command
    - name: execute-test
      inputs:
        parameters:
          - name: ip
      steps:
        - - name: execute-test
            arguments:
              {
                parameters:
                  [
                    {
                      name: cmd,
                      value: "python /src/examples/tests/e2e/home_page_test.py && cat /root/home-page.png",
                    },
                    { name: ip, value: "{{inputs.parameters.ip}}" },
                  ],
              }
            template: execute-command
        - - name: export-test-result
            arguments:
              { parameters: [{ name: ip, value: "{{inputs.parameters.ip}}" }] }
            template: export-test-result
    - name: export-test-result
      inputs:
        parameters:
          - name: ip
      container:
        name: export-test-result
        image: hnminh/execute-argo-flow-env:latest
        command: ["/bin/sh", "-c"]
        args:
          [
            "pwd && ls -la && sshpass -p 'root' scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@{{inputs.parameters.ip}}:/root/home-page.png / && ls -la && pwd",
          ]
      outputs:
        artifacts:
          - name: test-result
            path: /home-page.png
            archive:
              tar:
                # no compression (also accepts the standard gzip 1 to 9 values)
                compressionLevel: 0
    - name: set-up-execute-environment
      daemon: true
      inputs:
        artifacts:
          - name: argo-events-custom-trigger
            path: /src
            git:
              repo: https://github.com/minhhoangvn/argo-events-custom-trigger.git
      container:
        name: set-up-execute-environment
        image: hnminh/execute-argo-flow-env:latest
        ports:
          - containerPort: 22
          - containerPort: 80
          - containerPort: 443
        # It seems argo has issue with postStart and postStop lifecycle hook
        # https://github.com/argoproj/argo/issues/3410
        # lifecycle:
        #   postStart:
        #     exec:
        #       command:
        #         [
        #           "/bin/bash",
        #           "-c",
        #           "export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 && curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && echo 'deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list.d/google-chrome.list && apt update -y && apt list --upgradable && apt upgrade -y && apt-get install -y wget google-chrome-stable unzip xvfb libxi6 libgconf-2-4 ssh sshpass > /dev/null 2>&1 && mkdir /chrome-headless/ && wget https://chromedriver.storage.googleapis.com/87.0.4280.20/chromedriver_linux64.zip --directory-prefix=/chrome-headless && unzip /chrome-headless/chromedriver_linux64.zip -d /chrome-headless && mv /chrome-headless/chromedriver /usr/bin/chromedriver && chown root:root /usr/bin/chromedriver;echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config && echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config && service ssh start && echo -e 'root\nroot' | passwd",
        #         ]
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          failureThreshold: 10
