apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: e2e-jobs-
  labels:
    workflows.argoproj.io/archive-strategy: "always"
spec:
  entrypoint: execute-e2e
  templates:
    - name: execute-e2e
      container:
        image: python:3.8.6

        command: ["/bin/bash", -c]
        args:
          [
            "curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add;echo 'deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list.d/google-chrome.list;apt update && apt list --upgradable && apt upgrade;apt install -y wget google-chrome-stable unzip xvfb libxi6 libgconf-2-4;mkdir /chrome-headless/;wget https://chromedriver.storage.googleapis.com/87.0.4280.20/chromedriver_linux64.zip --directory-prefix=/chrome-headless;unzip /chrome-headless/chromedriver_linux64.zip -d /chrome-headless;mv /chrome-headless/chromedriver /usr/bin/chromedriver;chown root:root /usr/bin/chromedriver",
          ]
    - name: execute-environment
      container:
        image: python:3.8.6
      daemon: true
